### PR TITLE
added config

### PR DESCRIPTION
**Pull request by PetervDooren**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
This config should be in the bringup packages IMO

**Comment by PetervDooren** [comment]
I reason none of these parameters are robot specific, therefore it should not be in the bringup packages

**Comment by MatthijsBurgh** [comment]
Probably not, but we don't have any config outside the bringup packages.

**Comment by PetervDooren** [comment]
I dont think thats a bad thing. These are default parameters that can be overwritten

**Comment by MatthijsBurgh** [comment]
See comment in other PR

**Review by MatthijsBurgh — APPROVED** [review]

**Pull request merged**
